# Generated by Django 5.0.6 on 2024-06-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_account_first_name_remove_account_last_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
