# Generated by Django 5.0.6 on 2024-06-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='business_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
