# Generated by Django 5.0.6 on 2024-06-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='contact_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
