# Generated by Django 5.0.6 on 2024-06-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='business_name',
        ),
        migrations.AlterField(
            model_name='store',
            name='store_url',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
