# Generated by Django 5.0.6 on 2024-07-03 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_store_delete_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('tx_id', models.CharField(max_length=100)),
                ('recipient', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='store',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_crypto', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='accounts.store')),
            ],
        ),
    ]
