# Generated by Django 5.0.6 on 2024-07-05 02:54

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='token',
            field=models.CharField(default=accounts.models.Account.generate_token, editable=False, max_length=32),
        ),
    ]
