# Generated by Django 5.0.6 on 2024-07-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_account_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='amount_bch',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='token',
            new_name='transaction_token',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
