# Generated by Django 5.0.6 on 2024-07-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_amount_transaction_amount_bch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_fiat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_bch',
            field=models.IntegerField(),
        ),
    ]
