# Generated by Django 5.0.6 on 2024-07-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_transaction_amount_fiat_alter_transaction_amount_bch'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account_token',
            field=models.CharField(default='x', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_bch',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_fiat',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recipient',
            field=models.CharField(default='x', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
