# Generated by Django 5.0.6 on 2024-07-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_transaction_account_token_transaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='PHP', max_length=100),
        ),
    ]
