# Generated by Django 5.0.6 on 2024-07-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_transaction_status_transaction_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
