# Generated by Django 5.0.6 on 2024-07-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_wallet_is_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_paid',
            field=models.IntegerField(null=True),
        ),
    ]
