# Generated by Django 5.0.6 on 2024-07-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_transaction_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount_bch',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_paid',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
    ]
