# Generated by Django 5.0.6 on 2024-07-15 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_transaction_amount_bch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount_bch',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount_fiat',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount_paid',
        ),
    ]
