# Generated by Django 5.0.6 on 2024-07-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_transaction_amount_bch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_bch',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_fiat',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_paid',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
    ]
