# Generated by Django 5.0.6 on 2024-07-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_transaction_amount_bch_transaction_amount_fiat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='address_index',
            field=models.IntegerField(default=0),
        ),
    ]
